manual/using.html

The original author did a good job making readable xml using the HTML escape syntax, but I just noticed a few stray spaces when I copied the build.xml to start my own project.
Before:
After:

Clean up whitespace in build.xml example

---

src/main/org/apache/tools/ant/taskdefs/optional/ssh/ScpToMessage.java

1024 byte buffer size is insufficient for transfering large files over faster (> 100Mbit) networks. We are transfering files tens or hundreds MB in size and transfer speed was 1MB/s. After increasing the buffer size too 100KB we are getting transfer speeds up to 60MB/s. Please consider increasing the BUFFER_SIZE in the next Ant release. Thanks, Peter

increase buffer size to improve transfer speed

---

src/etc/testcases/taskdefs/copy.xml
src/main/org/apache/tools/ant/util/ResourceUtils.java
src/tests/junit/org/apache/tools/ant/taskdefs/CopyTest.java

The commit here includes a fix for the issue reported in https://bz.apache.org/bugzilla/show_bug.cgi?id=60644. As described in that issue, the copy task corrupts the source file(s) that's being copied in cases where the target file points back to the source file through symlink.
The commit here (intentionally) handles/fixes this issue in core/central location and not just in the Copy task so that all such copy operations (through the `ResourceUtils`) now have the safeguard to ensure that such copying doesn't cause the source file corruption and the copying itself is skipped if the source and destination are the same resource.
This commit also includes a testcase to verify and fix the issue.
This PR is against the 1.9.x branch. Once tested, approved and merged, I can make corresponding …

[1.9.x branch] BZ-60644 Fix file corruption during copy task

---

WHATSNEW
src/main/org/apache/tools/ant/taskdefs/Zip.java

As suggested in https://bz.apache.org/bugzilla/show_bug.cgi?id=19516, the change in this PR uses `java.io.BufferedInputStream` which can take an underlying `InputStream` and provide `mark` support on the input stream. This should prevent loading a large amount of data into memory, in certain cases, in the `Zip` task.
If this PR is approved, I'll then backport this pretty straightforward change to 1.9.x branch too.

[master] Changes for BZ-19516 

---

src/main/org/apache/tools/ant/taskdefs/AugmentReference.java

Reference https://bz.apache.org/bugzilla/show_bug.cgi?id=62655
The manual of the augment task[1] states that it's supposed to throw a `BuildException` if the referenced id value isn't known. I admit that the bugzilla is more about the id attribute not being specified whereas the manual seems to talk about the value of id being unknown reference, but I think the issue itself can be considered valid.
The referenced bugzilla issue shows that it throws an `IllegalStateException`. That exception then does indeed get thrown as a BuildException[2] but the `reason` that gets reported to the build listeners[3] is the original cause (in this case the `IllegalStateException`).
The commit here is trivial and it throws the `BuildException` from the `augment` task when either `id` isn't specified or it …

bz-62655 throw a BuildException from augment task 

---

manual/Tasks/junitlauncher.html
manual/Tasks/link.html

For 100% compliance, all HTML documents in the manual should add `<!DOCTYPE html>` and replace `<meta http-equiv="Content-Language" content="en-us">` with `<html lang="en-us">`

Use valid markup

---

src/main/org/apache/tools/ant/taskdefs/Jar.java
src/main/org/apache/tools/ant/taskdefs/SignJar.java
src/main/org/apache/tools/ant/types/PatternSet.java
src/main/org/apache/tools/zip/ZipFile.java
src/main/org/apache/tools/zip/ZipOutputStream.java

http to https changes in references also introduced Java 5 to 8 changes, so let's be consistent

Refer to Java 8 documentation for consistency

---

src/main/org/apache/tools/ant/BuildException.java
src/main/org/apache/tools/ant/taskdefs/Checksum.java
src/main/org/apache/tools/ant/taskdefs/condition/Equals.java
src/main/org/apache/tools/ant/taskdefs/cvslib/RCSFile.java
src/main/org/apache/tools/ant/taskdefs/optional/junit/JUnitTestRunner.java
src/main/org/apache/tools/ant/taskdefs/optional/unix/Symlink.java
src/main/org/apache/tools/ant/types/Commandline.java

Hello, we're developing an automated system that detects inconsistent variable names in a large software project. Our system checks if each variable name is consistent with the other variables in its usage, and proposes correct candidates if inconsistency is found. This is a part of academic research that we hope to publish soon, but as a part of the evaluation, we applied our systems to your projects and got a few interesting results. We carefully reviewed our system output and manually created a patch to correct a few variable names. We would be delighted if this patch is found to be useful. If you have a question or suggestion regarding this patch, we'd happily answer. Thank you.
P.S. our patch is purely for readability purposes and does not change any functionality. A couple of issues …

Made some variable names more consistent with the other parts.

---

manual/Tasks/mkdir.html

Correct "Does nothing if the directory already exist." to "Does nothing if the directory already **exists**."

Correct a typo

---

src/etc/junit-frames-saxon.xsl
src/etc/junit-noframes-saxon.xsl

Previously it was possible to create illegal HTML, by copying control characters from the XML. This fixes that by escaping them.

Avoid illegal control characters in HTML

---

WHATSNEW
manual/properties.html
src/etc/testcases/taskdefs/optional/echoproperties.xml
src/main/org/apache/tools/ant/Project.java
src/main/org/apache/tools/ant/PropertyHelper.java
src/main/org/apache/tools/ant/property/LocalProperties.java
src/main/org/apache/tools/ant/property/LocalPropertyStack.java
src/main/org/apache/tools/ant/types/PropertySet.java
src/tests/junit/org/apache/tools/ant/PropertyHelperTest.java
src/tests/junit/org/apache/tools/ant/taskdefs/optional/EchoPropertiesTest.java

add a new delegate that enumerates property names to `PropertyHelper` and use it in `PropertySet` in order to fix https://bz.apache.org/bugzilla/show_bug.cgi?id=50179
This is an alternative to #126

Property enumerator

---

manual/Tasks/ear.html
manual/Tasks/exec.html
manual/Tasks/jar.html
manual/Tasks/javac.html
manual/Tasks/javadoc.html
manual/Tasks/javah.html
manual/Tasks/junitreport.html
manual/Tasks/script.html
manual/Tasks/splash.html
manual/Tasks/style.html
manual/Types/mapper.html
manual/Types/regexp.html
manual/develop.html
manual/install.html
manual/platform.html
manual/running.html
manual/tutorial-HelloWorldWithAnt.html
manual/tutorial-tasks-filesets-properties.html

Updated the manual to reflect ant 1.10 requires jdk 8
Removed novell from platforms as no current jdk seems to be available for that platform

Jkf 1.10 requires jdk8

---

manual/Tasks/concat.html
src/main/org/apache/tools/ant/taskdefs/Concat.java
src/tests/antunit/taskdefs/concat-test.xml

I propose this to solve https://bz.apache.org/bugzilla/show_bug.cgi?id=64855
To implement optional filtering before concatenation I moved the end-of-file-linebreak-fix into it's own LastLineFixingReader so that MultiReader.nextReader() can apply line-break-fixing and/or filtering on demand.

#64855 Add filterbeforeconcat option to Concat

---

CONTRIBUTORS
contributors.xml
src/main/org/apache/tools/zip/ZipOutputStream.java
src/tests/junit/org/apache/tools/zip/ZipOutputStreamTest.java

`java.util.zip.ZipOutputStream` extends from `java.util.zip.DeflaterOutputStream` which overrides `void write(int b)` to redirect its calls to `void write(byte[] b, int off, int len)`.
`org.apache.tools.zip.ZipOutputStream` doesn't extend the same class and currently doesn't override `void write(int b)`. This means that calls to this method end up in `FilterOutputStream.write(int b)`, which in turn passes them through to the underlying `OutputStream`. This bypasses all the logic in `ZipOutputStream.write(byte[] b, int offset, int len)` (deflation and whatnot) which produces corrupted ZIP files.
One example where the method `void write(int b)` is ultimately invoked is by calling `java.util.jar.Manifest.write(zipOutputStream)`.
This PR fixes this by overriding the method `void write(int b)` …

Override ZipOutputStream.write(int)

---

manual/install.html

File separator in Windows is backslash instead of slash.

correct a typo in the install part of manual (file separator)

---

CONTRIBUTORS
contributors.xml
src/main/org/apache/tools/ant/AntClassLoader.java

The [Javadoc for `ClassLoader#findResource(String)`](https://docs.oracle.com/javase/8/docs/api/java/lang/ClassLoader.html#findResource-java.lang.String-) states:
> Class loader implementations should override this method to specify where to find resources.
`AntClassLoader` doesn't do this. Jenkins needed this back in 2011, so Kohsuke Kawaguchi (the creator of Jenkins) implemented a workaround in [this Jenkins core commit](https://github.com/jenkinsci/jenkins/commit/601cb6bb43):
```
commit 601cb6bb43
Author: Kohsuke Kawaguchi <kk@kohsuke.org>
Date:   Mon Oct 10 02:49:45 2011
implement findResource(
```
I am now looking into unforking `AntClassLoader` in Jenkins core so that we can reuse the latest upstream version from Ant 1.10.x. As far as I can tell the fix remains valid and should be …

Implement `ClassLoader#findResource(String)`

---

src/main/org/apache/tools/ant/AntClassLoader.java

See [#149 (comment)](https://github.com/apache/ant/pull/149#issuecomment-884318912). I verified that without this fix, I could reproduce the original problem described by Kohsuke Kawaguchi in [JENKINS-22310 (comment)](https://issues.jenkins.io/browse/JENKINS-22310?focusedCommentId=197405&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-197405). I verified that with this fix, I could no longer reproduce the original problem.

findResources(String, boolean) can unnecessarily search the parent

---

src/main/org/apache/tools/ant/listener/MailLogger.java

Unfortunately, the code is duplicated due to different logging in different objects.

Support Jakarta Mail in MailLogger

---

src/main/org/apache/tools/ant/taskdefs/optional/junitlauncher/confined/Constants.java
src/main/org/apache/tools/ant/taskdefs/optional/junitlauncher/confined/ListenerDefinition.java

It is a continuation of https://github.com/apache/ant/pull/168. Looks like I missed to update `toForkedRepresentation`/`fromForkedRepresentation` methods.

junitlauncher - Fixed extension attribute support for listeners

---

manual/Tasks/get.html
src/main/org/apache/tools/ant/taskdefs/Get.java

Most clients do not send the Authorization header on redirects by default; because of security issues.
The ant:get task instead, always sends the Authorization header to the redirected location.
This PR makes this behavior configurable. The optional attribute "authenticateOnRedirect" can be set to "false".
I'm not a security expert. Therefore I didn't change the default behavior to avoid breaking existing Ant scripts. This means, "authenticateOnRedirect" defaults to "true". But maybe it would be better to change this.
_Example: getting an artifact from AWS CodeArtifact which redirects to a pre signed URL and therefore mustn't contain the Authorization header:_
```
<get src="https://codeartifact-url/..." username="aws" password="<secret>" dest="..." authenticateOnRedirect="false">
<header …
```

Allow ant:get task to disable authentication on redirect.

---

fetch.xml

Since the `<remoterepo>` tag is not in the scope of the `<resolve>` target, fetching artifacts from repositories different from Maven
Central fails (e.g. JAI).

Fix retrieval from non-default repositories

---

src/main/org/apache/tools/tar/TarUtils.java

This fixes parsing of archives produced on macOS.
See the discussion in https://github.com/ibmruntimes/Semeru-Runtimes/issues/15.

Names end before the first NULL (not the last)

---

src/script/ant

The existing use of `tr` doesn't distinguish between Java 8 and Java 18; see https://github.com/apache/ant/commit/bbe6859b2f57a2c9dcb51e269527f3c18a74aa1d#commitcomment-90131350 - this fixes that.

Fix detection of java.specification.version

---

src/main/org/apache/tools/ant/taskdefs/optional/ReplaceRegExp.java

Currently, if an IOException occurs in ReplaceRegExp or a file is missing, the task logs the error, but does not fail.  This pull request has ReplaceRegExp throw a BuildException if the task encounters an IOException or a file is missing.
A failOnError attribute is also added that only affects these newly thrown BuildExceptions.  Existing BuildExceptions that were thrown won't be affected by the failOnError attribute, and backwards compatibility can be maintained with failOnError=false.

Throw BuildExceptions in ReplaceRegExp for IOExceptions and missing files

---

src/main/org/apache/tools/ant/taskdefs/optional/junitlauncher/LauncherSupport.java

I realized that running tests using ant was much slower than running them from the IDE. The culprit was the legacy-xml reporter.
Using an unbuffered Output is very slow, even if you are using an .m2 disk..

Buffer for more Speed

---

manual/using.html

documentation says the attribute name for `<compilerarg>` is arg, but it's value. Updated doc.

fix <compilerarg> example documentation in manual

---

src/main/org/apache/tools/ant/taskdefs/optional/ssh/Scp.java

Consider the last occurrence of ':' while getting the indexOfPath as IPv6 address has more than one ':'.

BUG-ID : 59160 , fix extracting host for ipv6 address

---

CONTRIBUTORS
contributors.xml
src/main/org/apache/tools/ant/util/PermissionUtils.java
src/tests/junit/org/apache/tools/ant/util/PermissionUtilsTest.java

Currently `PermissionUtils.FileType.of` returns `REGULAR_FILE` instead of `SYMLINK` for sym links.

Fix PermissionUtils.FileType.of for sym links

---

WHATSNEW
manual/Tasks/mail.html
manual/listeners.html
src/main/org/apache/tools/ant/listener/MailLogger.java
src/main/org/apache/tools/ant/taskdefs/email/EmailTask.java
src/main/org/apache/tools/ant/taskdefs/email/JakartaMimeMailer.java
src/main/org/apache/tools/ant/taskdefs/email/Mailer.java
src/main/org/apache/tools/ant/taskdefs/email/MimeMailer.java

Bugzilla Report https://bz.apache.org/bugzilla/show_bug.cgi?id=69416
I'd like to have a second pair of eyes here as I don't really have a proper way to test it and all I can do is look at the code and say "looks fine".

improve security of TLS handling in MimeMailers

---

src/main/org/apache/tools/ant/types/ResourceCollection.java

I came across this while working on a custom Ant task. I saw what I think is the ResourceCollection stream() method eagerly loading elements when creating a stream. Not sure if that was intentional or not. If it is, feel free to close the PR.  If not, I've created this to update it to use the StreamSupport factory method and a spliterator. I think this is how the JDK Collection creates the stream. This will make using things like findFirst a bit faster as it won't have to load every element to find the first.

Use StreamSupport and spliterator to create a stream for ResourceCollection
